[package]
name = "enmesh-firmware-heltec-esp32"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
common = { path = "../../common" }
enmesh-firmware = { path = "../../enmesh" }
soc-esp32 = { path = "../../soc/esp32", features = ["esp32s3"] }

# screen drivers
ssd1306 = { version = "*", optional = true}
ssd1680 = { version = "*", optional = true}
st7735 = { version = "*", optional = true}

# FIXME local crates necessary for build (should be imported form soc_esp32)
embassy-executor = { version = "*", features = ["log"] }
[dependencies.esp-rtos]
git = "https://github.com/esp-rs/esp-hal"
features = ["embassy", "esp-radio", "esp-alloc"]

#-------------------------------------------------------------------------------
[features]

disable-esp32-radio = [
# conserve power - disable WiFi and BLE support
]

enable-backtrace = [
# provide a backtrace upon panic!
    "soc-esp32/esp-backtrace-panic"
]

# board support by name
#-------------------------------------------------------------------------------
wifi_lora_32 = [
# [WiFi LoRa 32 v3](https://heltec.org/project/wifi-lora-32-v3/)
# [WiFi LoRa 32 v4](https://heltec.org/project/wifi-lora-32-v4/)
    "_screen-ssd1306"
]

wireless_stick = [
# [Wireless Stick Lite](https://heltec.org/project/wireless-stick-lite-v2/)
]

wireless_stick_v3 = [
# [Wireless Stick Lite](https://heltec.org/project/wireless-stick-lite-v3/)
    "_screen-ssd1306"
]

wireless_tracker = [
# [Wireless Tracker](https://heltec.org/project/wireless-tracker/)
    "_screen-st7735",
    "_gps"
]

wireless_paper = [
# [Wireless Paper](https://heltec.org/project/wireless-paper/)
    "_screen-ssd1680",
]

# internal features
#-------------------------------------------------------------------------------
_gps = []

_use_screen = []
_screen-ssd1306 =  [ "_use_screen", "ssd1306" ]
_screen-st7735  =  [ "_use_screen", "st7735" ]
_screen-ssd1680 =  [ "_use_screen", "ssd1680" ]


#-------------------------------------------------------------------------------
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
lto = 'fat'
opt-level = 's'
overflow-checks = false
incremental = false
