[package]
name = "enmesh-firmware-heltec-esp32"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
common = { path = "../../common" }
enmesh-firmware = { path = "../../enmesh" }
soc-esp32 = { path = "../../soc/esp32", features = ["esp32s3"] }

# screen drivers
# ssd1306 = { optional = true, version = "*", features = ["async", "graphics"] }
# FIXME - current revisions don't support async (https://github.com/rust-embedded-community/ssd1306/issues/219)
ssd1306 = { optional = true, git = "https://github.com/rust-embedded-community/ssd1306.git", rev = "f3a2f7aca421fbf3ddda45ecef0dfd1f0f12330e", features = [
    "async",
    "graphics",
]}
# epd-rs = { optional = true, version = "*", features = ["log", "async"] }
epd-rs = { optional = true, git = "https://github.com/redengin/epd-rs.git", features = ["log", "async"] }
# epd-rs = { optional = true, path = "../../../../../epd-rs", features = ["log", "async"] }
# st7735 = { version = "*", optional = true}
display-interface-spi = "*"

# FIXME local crates necessary for build (should be imported form soc_esp32)
embassy-executor = { version = "*", features = ["log"] }
[dependencies.esp-rtos]
git = "https://github.com/esp-rs/esp-hal"
features = ["embassy", "esp-radio", "esp-alloc"]

#-------------------------------------------------------------------------------
[features]

disable-esp32-radio = [
    # conserve power - disable WiFi and BLE support
]

disable-ux = [
    # conserve power by disabling screen and UX
]

enable-backtrace = [
    # provide a backtrace upon panic!
    "soc-esp32/esp-backtrace-panic",
]

# board support by name
#-------------------------------------------------------------------------------
wifi_lora_32-v3 = [
    # [WiFi LoRa 32 v3](https://heltec.org/project/wifi-lora-32-v3/)
    "dep:ssd1306",     # uses an OLED screen
    "_screen-ssd1306",
]
wifi_lora_32-v4 = [
    # [WiFi LoRa 32 v4](https://heltec.org/project/wifi-lora-32-v4/)
    "dep:ssd1306",     # uses an OLED screen
    "_screen-ssd1306",
]

wireless_stick_v2 = [
    # [Wireless Stick Lite](https://heltec.org/project/wireless-stick-lite-v2/)
]

wireless_stick_v3 = [
    # [Wireless Stick Lite](https://heltec.org/project/wireless-stick-v3/)
    # FIXME wireless stick v3 schematic doesn't identify the LoRa BUSY pin
    "dep:ssd1306",     # uses an OLED screen
    "_screen-ssd1306",
]

wireless_tracker = [
    # [Wireless Tracker](https://heltec.org/project/wireless-tracker/)
    # "_screen-st7735",
    # "_gps",
]

wireless_paper = [
    # [Wireless Paper](https://heltec.org/project/wireless-paper/)
    "dep:epd-rs",  # uses an EINK screen
    "_screen-epd",
]

# internal features
#-------------------------------------------------------------------------------
# _gps = []
_screen-ssd1306 = []
_screen-epd = []

#-------------------------------------------------------------------------------
[profile.dev]
opt-level = "s" # optimize for size to fit on the SoC flash

[profile.release]
opt-level = "s"         # optimize for size to fit on the SoC flash
codegen-units = 1       # LLVM can perform better optimizations using a single thread
debug = 2
lto = 'fat'
overflow-checks = false
incremental = false
