mod generators;

/// provide write trait for File I/O
use std::io::Write;

fn main() {
    println!("Generating bitmaps for assets...");
    println!("cargo:rerun-if-changed=ALWAYS");

    /// folder for assets
    const ASSETS_PATH: &str = "assets";
    /// folder for generated content
    const GENERARTED_PATH: &str = "generated/src";
    let dest_dir = std::path::Path::new(GENERARTED_PATH);
    std::fs::File::create(dest_dir.join("lib.rs")).unwrap()
        .write_all(
            b"\
            //! This file was generated by build.rs - MODIFICATIONS will be OVERWRITTEN\n\
            #![no_std]\n\
            \n\
            pub mod fonts;\n\
            \n\
            pub mod images;\n\
            ",
        )
        .unwrap();


    // subfolder for mod fonts
    let fonts_dir = dest_dir.join("fonts");
    // begin mod.rs for fonts
    std::fs::create_dir_all(&fonts_dir).unwrap();
    let mut fonts_mod_rs = std::fs::File::create(fonts_dir.join("mod.rs")).unwrap();
    fonts_mod_rs
        .write_all(
            b"\
            //! This file was generated by build.rs - MODIFICATIONS will be OVERWRITTEN\n\
            \n\
            ",
        )
        .unwrap();

    // subfolder for images
    let images_dir = dest_dir.join("images");
    // begin mod.rs for images
    std::fs::create_dir_all(&images_dir).unwrap();
    let mut images_mod_rs = std::fs::File::create(images_dir.join("mod.rs")).unwrap();
    images_mod_rs
        .write_all(
            b"\
            //! This file was generated by build.rs - MODIFICATIONS will be OVERWRITTEN\n\
            \n\
            /// provide the common crates via re-export\n\
            use common::*;\n\
            \n\
            ",
        )
        .unwrap();

    // read the entries in the assets folder
    for result in
        std::fs::read_dir(ASSETS_PATH).expect("ERROR: assets folder must exist at root of project")
    {
        if let Ok(entry) = result {
            // ignores subdirectories
            if entry.path().is_file() {
                // the file name extension to determine how to handle the file
                if let Some(extension) = entry.path().extension() {
                    /// provide access to transformations
                    use generators::*;
                    match extension
                        .to_ascii_uppercase()
                        .to_str()
                        .expect("ERROR: file name is not ascii")
                    {
                        "OTF" => ttf_generate(&entry.path(), &fonts_dir, &mut fonts_mod_rs),
                        "TTF" => ttf_generate(&entry.path(), &fonts_dir, &mut fonts_mod_rs),
                        "SVG" => svg_generate(&entry.path(), &images_dir, &mut images_mod_rs),
                        _ => {
                            println!("cargo::warning=Unrecognized asset {:?}", entry.file_name());
                        }
                    }
                }
            }
        }
    }
}
