[package]
name = "reticulum"
categories = ["network-programming"]
keywords = ["reticulum", "mesh", "radio", "async", "no_std"]
description = """
Rust implementation of the Reticulum Network Stack - a cryptographic,
decentralised, and resilient mesh networking protocol designed for
communication over any physical layer.

This project brings Reticulum's capabilities to the Rust ecosystem,
enabling both std and embedded environments.
"""
version = "0.1.0"
license-file = "LICENSE.md"
edition = "2024"
publish = true 

[dependencies]
# Random Number generator
rand_core = { version = "*", default-features = false }
sha2 = { version = "*", default-features = false }



[features]
# enable std support (default no-std)
std = []