[package]
name = "common"
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
log = "*"

# embedded utils
#-------------------------------------------------------------------------------
embedded-hal = "*"
embedded-hal-async = "*"
embedded-hal-bus = { version = "*", features = ["async"] }
static_cell = "*"
heapless = { version = "*", features = ["ufmt"] }
embedded-graphics = "*"
embedded-layout = "*"
#-------------------------------------------------------------------------------

# use the embassy RTOS
#-------------------------------------------------------------------------------
embassy-executor = { version = "*", features = ["log"] }
embassy-time = { version = "*", features = ["log"] }
embassy-embedded-hal = "*"
embassy-sync = { version = "*", features = ["log"] }
embassy-futures = { version = "*", features = ["log"] }
embassy-usb = { version = "*", features = ["log"] }
#-------------------------------------------------------------------------------

# Hardware drivers
#-------------------------------------------------------------------------------
# provide LORA radio drivers
lora-modulation = { version = "*", features = ["serde"] }
lora-phy = "*"

# screen support
display-interface = "*"
profont = "*"
#-------------------------------------------------------------------------------

# provide BLE Host
#-------------------------------------------------------------------------------
trouble-host = { version = "*", features = [
    "log",
    "peripheral",
    "gatt",
    "central",                      # required for security feature // FIXME  this shouldn't be necessary
    "security",
    "derive",                       # provide macros
    "default-packet-pool-mtu-1024", # max out BLE MTU size to maximize bandwidth
]}
#-------------------------------------------------------------------------------
